### ISSUE TITLE
Link to Concepts in vbnet/issues/65 404s

### ISSUE THREAD

**Issue by axtens** [exercism/docs#166]
In [vbnet/issues/71](https://github.com/exercism/vbnet/issues/71) there's a link to [Add prerequisites to Practice Exercises](https://github.com/exercism/vbnet/issues/65) which has a link to [Concepts](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/concepts.md). This last link 404s.

**Comment by iHiD** [comment]
@axtens That seems like an issue with that issue having the wrong link, rather than something that needs changing in docs?

**Comment by axtens** [comment]
So then it's not worth reporting? Or should I be reporting it in vbnet's issues? @iHiD

**Comment by iHiD** [comment]
I would comment on the issue itself saying "the links on this are wrong" and then the author of the issue can correct them. There's just no change to make in this repository, so the issue isn't actionable here, which makes it likely it'll sit here going stale.

As you have write access to the vbnet repo, I'm pretty sure you can actually just edit the issue and repoint the links as well if you want to.

**Comment by lukaskretzschmer** [comment]
Hello, I spent some time trying to find the correct link to update the respective md file, because that's the only contribution I can make and then I found out it was just an issue.
Anyway, here is the link:
[https://github.com/exercism/docs/blob/main/building/tracks/concepts.md](https://github.com/exercism/docs/blob/main/building/tracks/concepts.md)

**Comment by iHiD** [comment]
@lukaskretzschmer Thank you.
