### ISSUE TITLE
Link in "Practice Exercises" > "Shared files" is a 404

### ISSUE THREAD

**Issue by axtens** [exercism/docs#360]
In https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md in the section entitled in "Shared files" the text reads "Some files are not specific to individual exercises, but are instead applicable to all exercises. Check the documentation for more information." The word "documentation" is a link to https://github.com/exercism/docs/blob/main/docs/building/tracks/shared-files which is a 404

**Comment by ErikSchierboom** [comment]
The documentation is meant to be read from the docs section on exercism.org, not via the markdown files. This is because there is a post-processing step going on. The correct page is thus https://exercism.org/docs/building/tracks/practice-exercises and there the link does work. Sorry for the confusion.

p.s. did we link to the markdown files anywhere in the new track docs and is that how you've found it?
