### ISSUE TITLE
missing anchor links

### ISSUE THREAD

**Issue by ee7** [exercism/docs#377]
Reproduce:

1. Go to e.g. https://exercism.org/docs/building/tracks/icons
2. Click on a link that links internally within the page. e.g. Key feature icons (https://exercism.org/docs/building/tracks/icons#h-key-feature-icons)
3. Note that nothing happens

---

~And even on a page where we don't explicitly link to another part of that page, it is useful to send people links like:~

~https://exercism.org/docs/building/tracks/config-json#Concepts~

~which doesn't work currently.~

~Related: https://github.com/exercism/exercism/issues/5268~

Edit: Jeremy says below that the link should be to `#h-concepts`.

**Comment by iHiD** [comment]
There's two things here.

1. Anchor links are being reloaded as page links. That's a bug.
2. The link URLs are actually of the format `h-#{lowercased_title}` - e.g. `https://exercism.org/docs/building/tracks/config-json#h-concepts`. This is currently deliberate.

- For (1), I'd appreciate a bug report on exercism/exercism (it can just link back to this comment).
- For (2), we could change to the "GitHub" model of doing this if the markdown parser output `<a name="..."/>` rather than adding an `id` tag to links, but as `id` tags are used for other things such as CSS, I'm not willing to have non-prefixed ids be added to the dom. There is also a separate issue open in exercism/exercism for us adding a clickable anchor icon to the side of the headers as per GitHub to expose the links on click.

**Comment by ee7** [comment]
> For (1), I'd appreciate a bug report on exercism/exercism

Done: https://github.com/exercism/exercism/issues/6528

> There is also a separate issue open in exercism/exercism for us adding a clickable anchor icon to the side of the headers as per GitHub to expose the links on click.

Ah. To others: https://github.com/exercism/exercism/issues/6485

> This is currently deliberate.

> I'm not willing to have non-prefixed ids be added to the dom.

Got it.

Then I think we can close this issue in favor of the two issues linked in this comment. Please reopen this if I'm wrong.

**Comment by iHiD** [comment]
Thanks! :)
