### ISSUE TITLE
Show how to run non-leiningen tests on the Clojure page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/docs#60]
Right now the docs assume that you're using leiningen to run the suite, which you might not be:

http://help.exercism.io/getting-started-with-clojure.html

It would be useful to add some documentation about how to run them without it.

**Comment by canweriotnow** [comment]
To be clear, 'using leiningen to run the test suite' sounds like running `lein test` in a Clojure project, whereas the current instructions just call `lein exec` to load and execute a clj file...

Maybe this issue is outdated, but the current linked doc does show how to do the same thing (exec a test file) without leiningen: `java -cp clojure-1.5.1.jar clojure.main bob_test.clj`

**Comment by kytrinyx** [comment]
I've never actually written any clojure, and so I didn't realize that there's a difference between `lein test` and `lein exec`.

I think that the docs probably got updated, so I'll close this issue.

Thanks!
